version: "3.9"

services:
  webapp:
    restart: always
    build: .
    container_name: webapp
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    env_file:
      - ./.env
    command: bash entrypoint.sh
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:7.2.4
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  worker:
    build: .
    container_name: worker
    restart: always
    volumes:
      - ./:/app
    env_file:
      - ./.env
    depends_on:
      - redis
      - webapp
      - db
    command: 'celery -A pastebin worker -l info'

  beat:
    build: .
    container_name: beat
    restart: always
    volumes:
      - ./:/app
    env_file:
      - ./.env
    depends_on:
      - redis
      - webapp
      - worker
      - db
    command: 'celery -A pastebin beat -l info'

  flower:
    build: .
    container_name: flower
    env_file:
      - ./.env
    command: 'celery -A pastebin flower'
    volumes:
      - ./:/app
    depends_on:
      - worker
      - redis
    ports:
      - "5555:5555"


volumes:
  postgres_data: