version: "3.9"

services:
  webapp:
    restart: always
    build: .
    container_name: webapp
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - ./static:/app/static
    env_file:
      - ./.env
    command: bash entrypoint.sh
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:7.2.4
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  worker:
    build: .
    container_name: worker
    restart: always
    volumes:
      - ./:/app
    env_file:
      - ./.env
    command: 'celery -A pastebin worker -l info'
    depends_on:
      - redis
      - webapp
      - db

  beat:
    build: .
    container_name: beat
    restart: always
    volumes:
      - ./:/app
    env_file:
      - ./.env
    command: 'celery -A pastebin beat -l info'
    depends_on:
      - redis
      - webapp
      - worker
      - db

  flower:
    build: .
    container_name: flower
    env_file:
      - ./.env
    command: 'celery -A pastebin flower'
    volumes:
      - ./:/app
    ports:
      - "5555:5555"
    depends_on:
      - webapp
      - worker
      - redis

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    volumes:
      - ./static:/static
      - ./certbot/conf/:/etc/letsencrypt
      - ./certbot/www/:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - webapp

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www/:/var/www/certbot




volumes:
  postgres_data: