version: "3.9"

services:
  webapp:
    build: .
    container_name: webapp
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: bash entrypoint.sh
    depends_on:
      - db

  db:
    build:
      context: ./pg_cron
    container_name: postgres
    ports:
      - "5433:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: